var GLOBAL_NAMESPACE = 'vh';
// @codekit-append '../tools/_core.js';
// @codekit-append '../tools/vendor/jquery/1.9/_jquery.js';
// @codekit-append '../tools/vendor/waypoints/4.0.0/_waypoints.js';
// @codekit-append '../tools/helpers/global-helper/1.0/_global-helper.js';
// @codekit-append '../tools/helpers/mobile-helper/1.0/_mobile-helper.js';
// @codekit-append '../tools/helpers/desktop-helper/1.0/_desktop-helper.js';
// @codekit-append '../tools/modules/carousel/1.0/_carousel.js';
// @codekit-append '../tools/modules/overlay/1.0/_overlay.js';
// @codekit-append '../tools/modules/video/1.0/_video.js';
